/**
 * Trust Layer + "Et maintenant ?" for Hadak answers. Pure: says where an
 * answer comes from and proposes at most three in-app sections to open next.
 * Nothing here runs an action; every action is INFORMATIONAL (opening a page
 * section changes nothing).
 */
import type { NextAction } from '@/lib/rmeMoments';
import type { TruthLevel } from '@/lib/trust';

export type HadakLang = 'fr' | 'da' | 'en' | 'ar' | 'es';

/**
 * CLOCK: server clock. LIVE_DATA: every fact read from a live source.
 * RME_GUIDE: written RME guidance (possibly with some live figures), not
 * verified with an authority. AI: generated by a language model.
 */
export type ProvenanceBasis = 'CLOCK' | 'LIVE_DATA' | 'RME_GUIDE' | 'AI';

export type HadakProvenance = {
  level: TruthLevel;
  basis: ProvenanceBasis;
  /** Live sources actually read for this answer (e.g. "Open-Meteo"). */
  sources: string[];
};

/** What the route observed while building one answer. */
export type AnswerTrace = {
  /** Live sources that returned data. */
  live: string[];
  /** True when every fact in the answer came from `live` or the clock. */
  liveOnly: boolean;
  clock?: boolean;
  ai?: boolean;
};

export function newTrace(): AnswerTrace {
  return { live: [], liveOnly: false };
}

export function provenanceOf(trace: AnswerTrace): HadakProvenance {
  const sources = [...new Set(trace.live)];
  if (trace.ai) return { level: 'INFERRED', basis: 'AI', sources };
  if (trace.clock) return { level: 'MEASURED', basis: 'CLOCK', sources };
  if (trace.liveOnly && sources.length > 0) return { level: 'MEASURED', basis: 'LIVE_DATA', sources };
  return { level: 'INFERRED', basis: 'RME_GUIDE', sources };
}

type Section = 'route' | 'preparer' | 'maroc' | 'transfert' | 'sport';

const SECTIONS: Record<Section, { destination: string; label: Record<HadakLang, string>; reason: Record<HadakLang, string> }> = {
  route: {
    destination: '/#route',
    label: { fr: 'Calculer mon trajet', da: '7seb triq dyali', en: 'Plan my route', ar: 'احسب مساري', es: 'Calcular mi ruta' },
    reason: {
      // RME computes distance, duration and fuel per country; tolls and the
      // ferry ticket are not computed (the route page says so): 2026-10-05.
      fr: 'Distance, durée et carburant pays par pays (prix officiels) ; péages et ferry à ajouter.',
      da: 'L-masafa, l-wa9t w lissans blad b blad (tmnan rasmiyin); péage w ferry zidhom nta.',
      en: 'Distance, duration and fuel country by country (official prices); add tolls and ferry yourself.',
      ar: 'المسافة والمدة والوقود بلداً بلداً (أسعار رسمية)؛ أضف رسوم الطريق والعبارة بنفسك.',
      es: 'Distancia, duración y combustible país por país (precios oficiales); añade peajes y ferry.',
    },
  },
  preparer: {
    destination: '/#preparer',
    label: { fr: 'Préparer mes papiers', da: 'Wajjed l-wraq', en: 'Prepare my papers', ar: 'حضّر وثائقي', es: 'Preparar mis papeles' },
    reason: {
      fr: 'La liste à cocher avant le départ : documents, voiture, SIM.',
      da: 'Liste 9bel ma tsafer: wraq, tomobil, SIM.',
      en: 'The checklist before leaving: documents, car, SIM.',
      ar: 'قائمة ما قبل السفر: الوثائق، السيارة، الشريحة.',
      es: 'La lista antes de salir: documentos, coche, SIM.',
    },
  },
  maroc: {
    destination: '/#maroc',
    label: { fr: 'Voir le Maroc aujourd’hui', da: 'Chouf l-Maghrib lyoum', en: 'Morocco today', ar: 'المغرب اليوم', es: 'Marruecos hoy' },
    reason: {
      fr: 'Météo, heure et prières des villes marocaines au même endroit.',
      da: 'T-ta9s, l-wa9t w salawat dyal l-mdun f blasa wa7da.',
      en: 'Weather, time and prayer times for Moroccan cities in one place.',
      ar: 'الطقس والوقت ومواقيت الصلاة للمدن المغربية في مكان واحد.',
      es: 'Tiempo, hora y oraciones de las ciudades marroquíes en un lugar.',
    },
  },
  transfert: {
    destination: '/#transfert',
    label: { fr: 'Comparer les transferts', da: 'Qaren tahwil l-flous', en: 'Compare transfers', ar: 'قارن التحويلات', es: 'Comparar envíos' },
    reason: {
      fr: 'Frais et taux affichés par les services d’envoi d’argent vers le Maroc.',
      da: 'L-frais w s-sarf dyal services dyal tahwil l-Maghrib.',
      en: 'Fees and rates shown by money-transfer services to Morocco.',
      ar: 'رسوم وأسعار خدمات تحويل الأموال إلى المغرب.',
      es: 'Comisiones y tipos de los servicios de envío a Marruecos.',
    },
  },
  sport: {
    destination: '/#sport-tv',
    label: { fr: 'Matchs et chaînes', da: 'Matchat w chaînes', en: 'Matches and channels', ar: 'المباريات والقنوات', es: 'Partidos y canales' },
    reason: {
      fr: 'Les prochains matchs et où les regarder.',
      da: 'Matchat jayin w fin tchoufhom.',
      en: 'Upcoming matches and where to watch them.',
      ar: 'المباريات القادمة وأين تشاهدها.',
      es: 'Próximos partidos y dónde verlos.',
    },
  },
};

const NEXT_BY_INTENT: Record<string, Section[]> = {
  trip: ['route', 'preparer', 'maroc'],
  ferry: ['route', 'preparer'],
  fuel: ['route'],
  docs: ['preparer', 'route'],
  sim: ['preparer'],
  weather: ['maroc', 'route'],
  prayer: ['maroc'],
  ramadan: ['maroc'],
  currency: ['transfert'],
  football: ['sport'],
  services: ['route'],
};

export function isHadakLang(value: unknown): value is HadakLang {
  return value === 'fr' || value === 'da' || value === 'en' || value === 'ar' || value === 'es';
}

/** 0 to 3 suggestions; none for time, school work or unrecognised questions. */
export function nextActionsFor(intent: string, lang: HadakLang = 'fr'): NextAction[] {
  const sections = Object.hasOwn(NEXT_BY_INTENT, intent) ? NEXT_BY_INTENT[intent] : [];
  return sections.slice(0, 3).map(section => ({
    id: `${intent}-${section}`,
    label: SECTIONS[section].label[lang],
    reason: SECTIONS[section].reason[lang],
    safety: 'INFORMATIONAL',
    destination: SECTIONS[section].destination,
  }));
}

const BADGE: Record<ProvenanceBasis, Record<HadakLang, string>> = {
  CLOCK: { fr: 'Heure officielle du Maroc', da: 'L-wa9t r-rasmi dyal l-Maghrib', en: 'Morocco official time', ar: 'التوقيت الرسمي للمغرب', es: 'Hora oficial de Marruecos' },
  LIVE_DATA: { fr: 'Donnée en direct', da: 'Ma3louma mubachira', en: 'Live data', ar: 'بيانات مباشرة', es: 'Dato en directo' },
  RME_GUIDE: { fr: 'Guide RME · à vérifier', da: 'Guide RME · t2akkad', en: 'RME guide · check it', ar: 'دليل RME · تحقّق منه', es: 'Guía RME · verifícalo' },
  AI: { fr: 'Réponse IA · à vérifier', da: 'Jawab IA · t2akkad', en: 'AI answer · check it', ar: 'إجابة ذكاء اصطناعي · تحقّق منها', es: 'Respuesta IA · verifícala' },
};

const WHY: Record<ProvenanceBasis, Record<HadakLang, string>> = {
  CLOCK: {
    fr: 'Calculée à partir de l’horloge du serveur, à l’heure légale du Maroc.',
    da: 'M7soba mn l-magana dyal serveur, b l-wa9t l-9anouni dyal l-Maghrib.',
    en: 'Computed from the server clock, in Morocco’s legal time.',
    ar: 'محسوبة من ساعة الخادم بالتوقيت القانوني للمغرب.',
    es: 'Calculada con el reloj del servidor, en la hora legal de Marruecos.',
  },
  LIVE_DATA: {
    fr: 'Lue à l’instant auprès de la source citée, sans ajout.',
    da: 'Tqrat daba mn l-masdar l-madkour, bla zyada.',
    en: 'Read just now from the named source, nothing added.',
    ar: 'مقروءة الآن من المصدر المذكور دون إضافة.',
    es: 'Leída ahora de la fuente citada, sin añadidos.',
  },
  RME_GUIDE: {
    fr: 'Conseils rédigés par RME, non vérifiés auprès d’une autorité : confirmez les règles et les prix avant de partir.',
    da: 'Nasa2i7 ktebhom RME, ma t2akkdouch m3a chi idara: t2akkad mn l-9awanin w l-as3ar 9bel ma tmshi.',
    en: 'Advice written by RME, not checked with an authority: confirm rules and prices before you go.',
    ar: 'نصائح كتبها RME ولم تُراجع مع جهة رسمية: تأكّد من القواعد والأسعار قبل السفر.',
    es: 'Consejos escritos por RME, no verificados con una autoridad: confirma normas y precios antes de salir.',
  },
  AI: {
    fr: 'Rédigée par une IA à partir de votre question : elle peut se tromper.',
    da: 'Ktebha IA mn so2al dyalk: ymken tghlat.',
    en: 'Written by an AI from your question: it can be wrong.',
    ar: 'كتبها ذكاء اصطناعي انطلاقاً من سؤالك: قد يخطئ.',
    es: 'Redactada por una IA a partir de tu pregunta: puede equivocarse.',
  },
};

const SOURCES_LABEL: Record<HadakLang, string> = { fr: 'Sources', da: 'L-masadir', en: 'Sources', ar: 'المصادر', es: 'Fuentes' };

export function describeProvenance(p: HadakProvenance, lang: HadakLang = 'fr'): { badge: string; why: string } {
  const colon = lang === 'fr' ? ' : ' : ': ';
  const sources = p.sources.length ? ` ${SOURCES_LABEL[lang]}${colon}${p.sources.join(', ')}.` : '';
  return { badge: BADGE[p.basis][lang], why: `${WHY[p.basis][lang]}${sources}` };
}

/** Provenance of the answers the app writes itself when the server is unreachable. */
export const OFFLINE_PROVENANCE: HadakProvenance = { level: 'INFERRED', basis: 'RME_GUIDE', sources: [] };
